name: Tests
on:
  push:
    branches-ignore:
      - all-contributors/**

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

  eslint:
    name: ESLint
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: yarn lint:eslint

  typescript:
    name: TypeScript
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: yarn lint:typescript

  test:
    name: Test
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn test:ci

  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn build
